package com.hzeng;

import javax.swing.*;
import java.awt.*;

public class test {

    public static void main(String[] args) {
        JFrame frame = new JFrame("test");
        frame.setContentPane(new test().editor);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private JPanel editor;
    private JTree tree1;
    private JEditorPane editorPane1;
    private JEditorPane editorPane2;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        editor = new JPanel();
        editor.setLayout(new BorderLayout(0, 0));
        tree1 = new JTree();
        editor.add(tree1, BorderLayout.WEST);
        final JScrollPane scrollPane1 = new JScrollPane();
        editor.add(scrollPane1, BorderLayout.EAST);
        editorPane1 = new JEditorPane();
        scrollPane1.setViewportView(editorPane1);
        final JScrollPane scrollPane2 = new JScrollPane();
        editor.add(scrollPane2, BorderLayout.CENTER);
        editorPane2 = new JEditorPane();
        scrollPane2.setViewportView(editorPane2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return editor;
    }

}
